replicaCount: 1
aiagent:
  image:
    repository: syesildag/aiagent
    tag: 0.1.2
  port: 3000
  targetPort: 3000
postgres:
  image: pgvector/pgvector:pg15
  database: postgres
  user: postgres
  password: postgres
  service:
    name: postgres-service
    port: 5432
    targetPort: 5432